services:
  web:
    build: ./web-app
    ports:
      - 5000:5000
    environment:
      - DB_HOST = ${MONGO_HOST}
    depends_on:
      - machine
      - db

  machine:
    build: ./machine-learning-client
    ports:
      - 1000:1000
    environment:
      - DB_HOST = ${MONGO_HOST}
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_USER=${MONGO_USERNAME}
      - MONGO_PASS=${MONGO_PASSWORD}
    volumes:
      - database:/data/db

volumes:
  database: