services:
  web:
    build: ./web-app
    ports:
      - 5000:5000
    environment:
    depends_on:
      - machine
      - db
    volumes:
      - ./files:/app/audiofiles

  machine:
    build: ./machine-learning-client
    ports:
      - 1000:1000
    environment:
      - ASSEMBLYAI_API_KEY = ${ASSEMBLYAI_API_KEY}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./files:/app/audiofiles

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - MONGO_USER=${MONGO_USERNAME}
      - MONGO_PASS=${MONGO_PASSWORD}
    volumes:
      - database:/data/db

volumes:
  database:

networks:
  default:
    driver: bridge