services:
  web:
    build: ./web-app
    ports:
      - 1001:1001
    environment:
      DB_HOST = mongodb://db/data
    depends_on:
      - machine
      - db
    command: npm start

  machine:
    build: ./machine-learning-client
    ports:
      - 1000:1000
    environment:
      DB_HOST = mongodb://db/data
    depends_on:
      - db

  db:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db

volumes:
  data: