name: Machine Learning Client Tests
on:
  pull_request:
    types: [opened, closed]
jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    steps:
      - uses: actions/checkout@v4
      - name: Enter Directory
        run: |
          cd machine-learning-client
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run the tests
        working-directory: ./machine-learning-client
        run: |
          python -m pip install pipenv
          pipenv install pytest
          pipenv --venv
          pipenv run python -m pytest