name: Web App Tests
on:
  pull_request:
    types: [opened, closed]
    branches: [main, master]
jobs:
  build_test:
    runs-on: ubuntu-latest
    timeout-minutes: 6
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
      - uses: actions/checkout@v4
      - name: Install Python
        uses: kojoru/prepare-pipenv@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Enter Directory
        run: |
          cd web-app
      - name: Run the tests
        run: |
          pipenv install
          pipenv --venv
          pipenv run python -m pytest